import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
  WorkflowCreatedPayload as ContractsWorkflowCreatedPayloadSchema,
  WorkflowDeletedPayload as ContractsWorkflowDeletedPayloadSchema,
  WorkflowDefinitionPatchRequestedPayload as ContractsWorkflowDefinitionPatchRequestedPayloadSchema,
  WorkflowNodeRunCompletedPayload as ContractsWorkflowNodeRunCompletedPayloadSchema,
  WorkflowNodeRunFailedPayload as ContractsWorkflowNodeRunFailedPayloadSchema,
  WorkflowNodeRunStartedPayload as ContractsWorkflowNodeRunStartedPayloadSchema,
  WorkflowRunCompletedPayload as ContractsWorkflowRunCompletedPayloadSchema,
  WorkflowRunPausedPayload as ContractsWorkflowRunPausedPayloadSchema,
  WorkflowRunResumedPayload as ContractsWorkflowRunResumedPayloadSchema,
  WorkflowRunStartedPayload as ContractsWorkflowRunStartedPayloadSchema,
  WorkflowRunStoppingPayload as ContractsWorkflowRunStoppingPayloadSchema,
  WorkflowUpdatedPayload as ContractsWorkflowUpdatedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;

export const WorkflowCreatedPayload = ContractsWorkflowCreatedPayloadSchema;
export const WorkflowUpdatedPayload = ContractsWorkflowUpdatedPayloadSchema;
export const WorkflowDeletedPayload = ContractsWorkflowDeletedPayloadSchema;
export const WorkflowRunStartedPayload = ContractsWorkflowRunStartedPayloadSchema;
export const WorkflowRunPausedPayload = ContractsWorkflowRunPausedPayloadSchema;
export const WorkflowRunResumedPayload = ContractsWorkflowRunResumedPayloadSchema;
export const WorkflowRunStoppingPayload = ContractsWorkflowRunStoppingPayloadSchema;
export const WorkflowRunCompletedPayload = ContractsWorkflowRunCompletedPayloadSchema;
export const WorkflowNodeRunStartedPayload = ContractsWorkflowNodeRunStartedPayloadSchema;
export const WorkflowNodeRunCompletedPayload = ContractsWorkflowNodeRunCompletedPayloadSchema;
export const WorkflowNodeRunFailedPayload = ContractsWorkflowNodeRunFailedPayloadSchema;
export const WorkflowDefinitionPatchRequestedPayload =
  ContractsWorkflowDefinitionPatchRequestedPayloadSchema;
